### ISSUE TITLE
Virtual Keyboard Issue

### ISSUE THREAD

**Issue by dmnckcmps2017** [MartyrPher/SMAPI-Android-Installer#66] opened 2020-02-14 03:59 UTC
While updating the SMAPI android the in game virtual keyboard stopped working. At first it appeared in the game but was a shaded out and the buttons didn't work then when I uninstalled then reinstalled the SMAPI  it crashed before the game started and completely disappeared. Idk what to do! Help please!

**Comment by MartyrPher** [comment] 2020-02-14 07:32
Do you have a log for the issue? Can you follow the directions on this site and post the link here?
https://smapi.io/log/

**Comment by xeasli** [comment] 2020-02-14 18:26
Hi, I'm currently experiencing the same issue. The buttons are greyed out and I can't really press them. Here's the log for mine, https://smapi.io/log/c90cb441d3854e8ebc921e45a9bd98e9 Thanks!

**Comment by dmnckcmps2017** [comment] 2020-02-14 20:43
Update: I completely uninstalled and reinstalled the game and smapi. I also updated the mods that go with the keyboard and it worked.

**Comment by xeasli** [comment] 2020-02-15 05:20
Tried uninstalling and reinstalling, and it still doesn't work for me :(

**Comment by dmnckcmps2017** [comment] 2020-02-15 06:12
I had to manually redownload the mods from nexus again with the latest versions. Delete the old mods (I only have item spawn and cheat menu) and don't make the same mistake I did and download the file that say android only in big red letters because that's for the older version of the game. Download the very first file.

**Comment by xeasli** [comment] 2020-02-15 06:32
I've already uninstalled all of my other mods prior to reinstalling, still nothing, though :( anyway I'll give it a try again later, thanks for the help!

**Comment by MartyrPher** [comment] 2020-02-17 07:44
Yup, Do not use the mods labeled Android as they are for the 1.3 version. VK is working as intended. Closing this issue.

**Closed by MartyrPher** 2020-02-17 07:44 UTC
